version: "3.8"

services:
  keystone-cms:
    build: .
    container_name: farmcity-cms
    restart: always
    ports:
      - "5000:3000"
    environment:
      - NODE_ENV=production
      - DATABASE_URL=file:./keystone.db
    volumes:
      - ./keystone-data:/app/keystone-data
